-- =========================================================
-- 11_TRANSACTIONS_PROCEDURES.SQL
-- Banking Transaction & Fraud Analytics Database
-- Data Engineering / Transaction Processing Layer
-- =========================================================


-- =========================================================
-- STEP 1: MAKE ALERT_ID AUTO-GENERATED
-- =========================================================

DO $$
BEGIN

    IF NOT EXISTS (
        SELECT 1
        FROM pg_attribute a
        JOIN pg_class c
            ON a.attrelid = c.oid
        JOIN pg_namespace n
            ON c.relnamespace = n.oid
        WHERE n.nspname = 'production'
          AND c.relname = 'fraud_alerts'
          AND a.attname = 'alert_id'
          AND a.attidentity <> ''
    ) THEN

        ALTER TABLE production.fraud_alerts
        ALTER COLUMN alert_id
        ADD GENERATED BY DEFAULT AS IDENTITY;

    END IF;

END;
$$;


-- =========================================================
-- STEP 2: SYNCHRONIZE ALERT_ID IDENTITY SEQUENCE
--
-- If fraud_alerts contains records, synchronize the
-- identity sequence with MAX(alert_id).
--
-- If the table is empty, do NOT call setval().
-- The identity sequence will generate the first valid ID.
-- =========================================================

DO $$
DECLARE
    v_sequence_name TEXT;
    v_max_alert_id BIGINT;
BEGIN

    -- Get the identity sequence name
    SELECT pg_get_serial_sequence(
        'production.fraud_alerts',
        'alert_id'
    )
    INTO v_sequence_name;


    -- Get the current maximum alert ID
    SELECT MAX(alert_id)
    INTO v_max_alert_id
    FROM production.fraud_alerts;


    -- Synchronize only when existing data is present
    IF v_sequence_name IS NOT NULL
       AND v_max_alert_id IS NOT NULL THEN

        PERFORM setval(
            v_sequence_name,
            v_max_alert_id,
            true
        );

    END IF;

END;
$$;


-- =========================================================
-- PROCEDURE 1: ADD FRAUD ALERT
-- =========================================================

CREATE OR REPLACE PROCEDURE production.add_fraud_alert(
    p_transaction_id INT,
    p_alert_type VARCHAR(50),
    p_risk_score DECIMAL(5,2),
    p_description VARCHAR(255),
    p_alert_status VARCHAR(30)
)
LANGUAGE plpgsql
AS $$
BEGIN

    -- -----------------------------------------------------
    -- Validate required parameters
    -- -----------------------------------------------------

    IF p_transaction_id IS NULL THEN

        RAISE EXCEPTION
            'Transaction ID cannot be NULL';

    END IF;


    IF p_alert_type IS NULL
       OR TRIM(p_alert_type) = '' THEN

        RAISE EXCEPTION
            'Alert type cannot be NULL or empty';

    END IF;


    IF p_risk_score IS NULL THEN

        RAISE EXCEPTION
            'Risk score cannot be NULL';

    END IF;


    IF p_alert_status IS NULL THEN

        RAISE EXCEPTION
            'Alert status cannot be NULL';

    END IF;


    -- -----------------------------------------------------
    -- Validate transaction existence
    -- -----------------------------------------------------

    IF NOT EXISTS (
        SELECT 1
        FROM production.transactions
        WHERE transaction_id = p_transaction_id
    ) THEN

        RAISE EXCEPTION
            'Transaction % does not exist',
            p_transaction_id;

    END IF;


    -- -----------------------------------------------------
    -- Validate risk score
    -- -----------------------------------------------------

    IF p_risk_score < 0
       OR p_risk_score > 100 THEN

        RAISE EXCEPTION
            'Risk score must be between 0 and 100';

    END IF;


    -- -----------------------------------------------------
    -- Validate alert status
    -- -----------------------------------------------------

    IF p_alert_status NOT IN (
        'Open',
        'Investigating',
        'Resolved',
        'False Positive'
    ) THEN

        RAISE EXCEPTION
            'Invalid fraud alert status: %',
            p_alert_status;

    END IF;


    -- -----------------------------------------------------
    -- Prevent duplicate alert insertion
    -- -----------------------------------------------------

    IF EXISTS (
        SELECT 1
        FROM production.fraud_alerts
        WHERE transaction_id = p_transaction_id
          AND alert_type = p_alert_type
          AND risk_score = p_risk_score
          AND alert_status = p_alert_status
    ) THEN

        RAISE NOTICE
            'Identical fraud alert already exists for transaction %',
            p_transaction_id;

        RETURN;

    END IF;


    -- -----------------------------------------------------
    -- Insert fraud alert
    -- alert_id is generated automatically
    -- -----------------------------------------------------

    INSERT INTO production.fraud_alerts (
        transaction_id,
        alert_type,
        risk_score,
        description,
        created_at,
        alert_status
    )

    VALUES (
        p_transaction_id,
        p_alert_type,
        p_risk_score,
        p_description,
        CURRENT_TIMESTAMP,
        p_alert_status
    );


    RAISE NOTICE
        'Fraud alert added successfully for transaction %',
        p_transaction_id;

END;
$$;


-- =========================================================
-- TEST 1: ADD FRAUD ALERT
-- Idempotent test
-- =========================================================

DO $$
DECLARE
    v_transaction_id INT;
BEGIN

    SELECT transaction_id
    INTO v_transaction_id
    FROM production.transactions
    ORDER BY transaction_id
    LIMIT 1;


    IF v_transaction_id IS NOT NULL THEN

        CALL production.add_fraud_alert(
            v_transaction_id,
            'Procedure Test',
            85.50,
            'Test fraud alert generated by procedure validation',
            'Open'
        );

    ELSE

        RAISE NOTICE
            'TEST 1 skipped: No transactions found';

    END IF;

END;
$$;


-- =========================================================
-- VERIFY FRAUD ALERT
-- =========================================================

SELECT
    alert_id,
    transaction_id,
    alert_type,
    risk_score,
    alert_status
FROM production.fraud_alerts
ORDER BY alert_id DESC
LIMIT 5;


-- =========================================================
-- PROCEDURE 2: UPDATE FRAUD ALERT STATUS
-- =========================================================

CREATE OR REPLACE PROCEDURE production.update_fraud_alert_status(
    p_alert_id INT,
    p_new_status VARCHAR(30)
)
LANGUAGE plpgsql
AS $$
BEGIN

    -- -----------------------------------------------------
    -- Validate parameters
    -- -----------------------------------------------------

    IF p_alert_id IS NULL THEN

        RAISE EXCEPTION
            'Alert ID cannot be NULL';

    END IF;


    IF p_new_status IS NULL
       OR TRIM(p_new_status) = '' THEN

        RAISE EXCEPTION
            'New alert status cannot be NULL or empty';

    END IF;


    -- -----------------------------------------------------
    -- Validate status
    -- -----------------------------------------------------

    IF p_new_status NOT IN (
        'Open',
        'Investigating',
        'Resolved',
        'False Positive'
    ) THEN

        RAISE EXCEPTION
            'Invalid fraud alert status: %',
            p_new_status;

    END IF;


    -- -----------------------------------------------------
    -- Update status
    -- -----------------------------------------------------

    UPDATE production.fraud_alerts

    SET alert_status = p_new_status

    WHERE alert_id = p_alert_id;


    IF NOT FOUND THEN

        RAISE EXCEPTION
            'Fraud alert % does not exist',
            p_alert_id;

    END IF;


    RAISE NOTICE
        'Fraud alert % status updated successfully',
        p_alert_id;

END;
$$;


-- =========================================================
-- TEST 2: UPDATE LATEST PROCEDURE-TEST ALERT
-- =========================================================

DO $$
DECLARE
    v_latest_alert_id INT;
BEGIN

    SELECT alert_id
    INTO v_latest_alert_id
    FROM production.fraud_alerts
    WHERE alert_type = 'Procedure Test'
    ORDER BY alert_id DESC
    LIMIT 1;


    IF v_latest_alert_id IS NOT NULL THEN

        CALL production.update_fraud_alert_status(
            v_latest_alert_id,
            'Investigating'
        );

    ELSE

        RAISE NOTICE
            'TEST 2 skipped: No procedure-test fraud alert found';

    END IF;

END;
$$;


-- =========================================================
-- VERIFY FRAUD ALERT STATUS
-- =========================================================

SELECT
    alert_id,
    transaction_id,
    alert_type,
    risk_score,
    alert_status
FROM production.fraud_alerts
ORDER BY alert_id DESC
LIMIT 5;


-- =========================================================
-- PROCEDURE 3: TRANSFER MONEY
-- Transaction-safe money transfer
--
-- Both accounts are locked in a consistent account_id
-- order to reduce the risk of deadlocks during concurrent
-- transfers.
-- =========================================================

CREATE OR REPLACE PROCEDURE production.transfer_money(
    p_source_account_id INT,
    p_destination_account_id INT,
    p_amount DECIMAL(15,2)
)
LANGUAGE plpgsql
AS $$
DECLARE

    v_source_balance DECIMAL(15,2);
    v_source_currency VARCHAR(10);
    v_destination_currency VARCHAR(10);

BEGIN

    -- -----------------------------------------------------
    -- Validate parameters
    -- -----------------------------------------------------

    IF p_source_account_id IS NULL
       OR p_destination_account_id IS NULL THEN

        RAISE EXCEPTION
            'Source and destination account IDs cannot be NULL';

    END IF;


    IF p_amount IS NULL THEN

        RAISE EXCEPTION
            'Transfer amount cannot be NULL';

    END IF;


    -- -----------------------------------------------------
    -- Validate transfer amount
    -- -----------------------------------------------------

    IF p_amount <= 0 THEN

        RAISE EXCEPTION
            'Transfer amount must be greater than zero';

    END IF;


    -- -----------------------------------------------------
    -- Prevent transferring to the same account
    -- -----------------------------------------------------

    IF p_source_account_id = p_destination_account_id THEN

        RAISE EXCEPTION
            'Source and destination accounts must be different';

    END IF;


    -- -----------------------------------------------------
    -- Lock both accounts in a consistent order
    -- -----------------------------------------------------

    IF p_source_account_id < p_destination_account_id THEN

        -- Lock source first
        SELECT
            balance,
            currency
        INTO
            v_source_balance,
            v_source_currency
        FROM production.accounts
        WHERE account_id = p_source_account_id
        FOR UPDATE;


        IF NOT FOUND THEN

            RAISE EXCEPTION
                'Source account % does not exist',
                p_source_account_id;

        END IF;


        -- Lock destination second
        SELECT
            currency
        INTO
            v_destination_currency
        FROM production.accounts
        WHERE account_id = p_destination_account_id
        FOR UPDATE;


        IF NOT FOUND THEN

            RAISE EXCEPTION
                'Destination account % does not exist',
                p_destination_account_id;

        END IF;

    ELSE

        -- Lock destination first
        SELECT
            currency
        INTO
            v_destination_currency
        FROM production.accounts
        WHERE account_id = p_destination_account_id
        FOR UPDATE;


        IF NOT FOUND THEN

            RAISE EXCEPTION
                'Destination account % does not exist',
                p_destination_account_id;

        END IF;


        -- Lock source second
        SELECT
            balance,
            currency
        INTO
            v_source_balance,
            v_source_currency
        FROM production.accounts
        WHERE account_id = p_source_account_id
        FOR UPDATE;


        IF NOT FOUND THEN

            RAISE EXCEPTION
                'Source account % does not exist',
                p_source_account_id;

        END IF;

    END IF;


    -- -----------------------------------------------------
    -- Validate currencies
    -- -----------------------------------------------------

    IF v_source_currency <> v_destination_currency THEN

        RAISE EXCEPTION
            'Source and destination currencies do not match';

    END IF;


    -- -----------------------------------------------------
    -- Validate sufficient balance
    -- -----------------------------------------------------

    IF v_source_balance < p_amount THEN

        RAISE EXCEPTION
            'Insufficient balance';

    END IF;


    -- -----------------------------------------------------
    -- Deduct money from source account
    -- -----------------------------------------------------

    UPDATE production.accounts

    SET balance = balance - p_amount

    WHERE account_id = p_source_account_id;


    -- -----------------------------------------------------
    -- Add money to destination account
    -- -----------------------------------------------------

    UPDATE production.accounts

    SET balance = balance + p_amount

    WHERE account_id = p_destination_account_id;


    -- -----------------------------------------------------
    -- Transfer completed successfully
    -- -----------------------------------------------------

    RAISE NOTICE
        'Transfer completed successfully: % -> %, amount = %',
        p_source_account_id,
        p_destination_account_id,
        p_amount;

END;
$$;


-- =========================================================
-- TEST 3: SUCCESSFUL TRANSFER
--
-- Performs a real transfer and then reverses it.
-- This avoids using ROLLBACK inside a PL/pgSQL block.
-- =========================================================

DO $$
DECLARE

    v_source_account_id INT;
    v_destination_account_id INT;

    v_source_balance DECIMAL(15,2);
    v_source_balance_after DECIMAL(15,2);

    v_destination_balance_before DECIMAL(15,2);
    v_destination_balance_after DECIMAL(15,2);

    v_source_currency VARCHAR(10);

    v_final_source_balance DECIMAL(15,2);
    v_final_destination_balance DECIMAL(15,2);

BEGIN

    -- -----------------------------------------------------
    -- Find source account
    -- -----------------------------------------------------

    SELECT
        account_id,
        balance,
        currency
    INTO
        v_source_account_id,
        v_source_balance,
        v_source_currency
    FROM production.accounts
    WHERE balance >= 100
    ORDER BY account_id
    LIMIT 1;


    -- -----------------------------------------------------
    -- Find compatible destination account
    -- -----------------------------------------------------

    SELECT
        account_id,
        balance
    INTO
        v_destination_account_id,
        v_destination_balance_before
    FROM production.accounts
    WHERE account_id <> v_source_account_id
      AND currency = v_source_currency
    ORDER BY account_id
    LIMIT 1;


    IF v_source_account_id IS NOT NULL
       AND v_destination_account_id IS NOT NULL THEN

        BEGIN

            -- -------------------------------------------------
            -- Forward transfer
            -- -------------------------------------------------

            CALL production.transfer_money(
                v_source_account_id,
                v_destination_account_id,
                100
            );


            -- -------------------------------------------------
            -- Verify source balance
            -- -------------------------------------------------

            SELECT balance
            INTO v_source_balance_after
            FROM production.accounts
            WHERE account_id = v_source_account_id;


            -- -------------------------------------------------
            -- Verify destination balance
            -- -----------------------------------------------------

            SELECT balance
            INTO v_destination_balance_after
            FROM production.accounts
            WHERE account_id = v_destination_account_id;


            IF v_source_balance_after =
                   v_source_balance - 100

               AND v_destination_balance_after =
                   v_destination_balance_before + 100
            THEN

                RAISE NOTICE
                    'TEST 3 PASSED: Transfer balances updated correctly';

            ELSE

                RAISE EXCEPTION
                    'TEST 3 FAILED: Balance update validation failed';

            END IF;


            -- -------------------------------------------------
            -- Reverse transfer
            -- -------------------------------------------------

            CALL production.transfer_money(
                v_destination_account_id,
                v_source_account_id,
                100
            );


            -- -------------------------------------------------
            -- Verify restoration
            -- -------------------------------------------------

            SELECT balance
            INTO v_final_source_balance
            FROM production.accounts
            WHERE account_id = v_source_account_id;


            SELECT balance
            INTO v_final_destination_balance
            FROM production.accounts
            WHERE account_id = v_destination_account_id;


            IF v_final_source_balance = v_source_balance
               AND v_final_destination_balance =
                   v_destination_balance_before
            THEN

                RAISE NOTICE
                    'TEST 3 PASSED: Balances restored to original values';

            ELSE

                RAISE WARNING
                    'TEST 3 WARNING: Balances could not be fully restored - manual check required';

            END IF;


        EXCEPTION
            WHEN OTHERS THEN

                RAISE NOTICE
                    'TEST 3 FAILED: %',
                    SQLERRM;

        END;

    ELSE

        RAISE NOTICE
            'TEST 3 skipped: Two compatible accounts with sufficient balance are required';

    END IF;

END;
$$;


-- =========================================================
-- VERIFY ACCOUNT BALANCES
-- =========================================================

SELECT
    account_id,
    account_number,
    balance,
    currency
FROM production.accounts
ORDER BY account_id
LIMIT 10;


-- =========================================================
-- TEST 4: FAILED TRANSFER
-- Uses an amount larger than available balance.
--
-- The transfer must fail without changing the source
-- account balance.
-- =========================================================

DO $$
DECLARE

    v_source_account_id INT;
    v_destination_account_id INT;

    v_source_balance DECIMAL(15,2);
    v_balance_after DECIMAL(15,2);

BEGIN

    -- -----------------------------------------------------
    -- Select source account
    -- -----------------------------------------------------

    SELECT
        account_id,
        balance
    INTO
        v_source_account_id,
        v_source_balance
    FROM production.accounts
    ORDER BY account_id
    LIMIT 1;


    -- -----------------------------------------------------
    -- Select destination account
    -- -----------------------------------------------------

    SELECT account_id
    INTO v_destination_account_id
    FROM production.accounts
    WHERE account_id <> v_source_account_id
    ORDER BY account_id
    LIMIT 1;


    IF v_source_account_id IS NOT NULL
       AND v_destination_account_id IS NOT NULL THEN

        BEGIN

            -- -------------------------------------------------
            -- Attempt an impossible transfer
            -- -------------------------------------------------

            CALL production.transfer_money(
                v_source_account_id,
                v_destination_account_id,
                v_source_balance + 1000000
            );


            -- If the call succeeds, the test fails.
            RAISE EXCEPTION
                'TEST 4 FAILED: Transfer unexpectedly succeeded';


        EXCEPTION
            WHEN OTHERS THEN

                IF SQLERRM =
                   'TEST 4 FAILED: Transfer unexpectedly succeeded'
                THEN

                    RAISE;

                ELSE

                    RAISE NOTICE
                        'TEST 4 PASSED: Transfer failed as expected - %',
                        SQLERRM;

                END IF;

        END;


        -- -----------------------------------------------------
        -- Verify source balance remained unchanged
        -- -----------------------------------------------------

        SELECT balance
        INTO v_balance_after
        FROM production.accounts
        WHERE account_id = v_source_account_id;


        IF v_balance_after = v_source_balance THEN

            RAISE NOTICE
                'TEST 4 PASSED: Source balance remained unchanged';

        ELSE

            RAISE WARNING
                'TEST 4 WARNING: Source balance changed unexpectedly';

        END IF;


    ELSE

        RAISE NOTICE
            'TEST 4 skipped: At least two accounts are required';

    END IF;

END;
$$;


-- =========================================================
-- FINAL PROCEDURE CHECK
-- =========================================================

SELECT
    routine_schema,
    routine_name,
    routine_type
FROM information_schema.routines
WHERE routine_schema = 'production'
  AND routine_type = 'PROCEDURE'
ORDER BY
    routine_name;


-- =========================================================
-- END OF TRANSACTION PROCEDURES
-- =========================================================